[env:esp32cam]
platform = espressif32
board = esp32cam
framework = espidf
board_build.psram = enable
board_build.partitions = partitions.csv
monitor_speed = 115200  


build_flags =
    -D PROJECT_VER="1.0.0"
    -Wno-error=deprecated-declarations
    -Wno-error=format
    -DOV2640_SUPPORT=1
    -DCONFIG_OV2640_SUPPORT=1
    -DCONFIG_CAMERA_CORE0=1
    -DCONFIG_ESP_CONSOLE_UART_DEFAULT=1
    -DCONFIG_ESP_CONSOLE_UART=1
    -DCONFIG_ESP_CONSOLE_UART_NUM=0
    -DCONFIG_ESP_CONSOLE_UART_BAUDRATE=115200
    -DCONFIG_ESP_HTTP_SERVER_ENABLE=1
    -DCONFIG_ESP32_SPIRAM_SUPPORT=y
    -DCONFIG_SPIRAM_BOOT_INIT=y
    -DCONFIG_SPIRAM_TYPE_AUTO=y
    -DCONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY=y
    -DCONFIG_SPIRAM_USE_MALLOC=y
    -I$PROJECT_DIR/components/esp32-camera

lib_ignore = esp32-camera
#lib_extra_dirs = components