[env:esp32cam]
platform = espressif32
board = esp32cam
framework = espidf
board_build.psram = enable
board_build.partitions = partitions.csv
monitor_speed = 115200  


build_flags =
    -D PROJECT_VER="1.0.0"
    -Wno-error=deprecated-declarations
    -Wno-error=format
    -DCONFIG_SPIRAM=y
    -DOV2640_SUPPORT=1
    -DCONFIG_OV2640_SUPPORT=1
    -DCONFIG_CAMERA_CORE0=1
    -I$PROJECT_DIR/components/esp32-camera

lib_ignore = esp32-camera